### ISSUE TITLE
Limiting Splash Height

### ISSUE THREAD

**Issue by phz1** [hotdoy/grav-skeleton-hotdoy#7]
Hi,

first of all, thanks for creating this amazing theme/skeleton. I had no issues with it until I updated the theme. Updating drawers was fine. However I had set a max_height to all my pages with a splash element, and now it doesn't seem to apply at all. Any sort of css workaround I tried doesn't work either.

Thanks

**Comment by vincentrouleau** [comment]
Kinda hard to really tell without an example.
Was the max height on the page or on the splash?
If you post an url where I could see the issue, I could probably tell you how to fix it.

**Comment by phz1** [comment]
I currently only have it in a local environment. If it's really needed I can push it to somewhere.

Only the splash is supposed to be "cut" to 60% of the page, the idea is that the splash element would only serve as a header for all pages, with the name in the middle.

**Comment by vincentrouleau** [comment]
Just found a typo in the splash css. Ill send you something in a couple minutes

**Comment by phz1** [comment]
Thanks!
If you mean the writing of `spalsh`, I already fixed that and it didn't work.

**Comment by hotdoy** [comment]
45cc23a

**Comment by vincentrouleau** [comment]
https://github.com/hotdoy/grav-theme-hotdoy/commit/45cc23a096d482821612535f79509c1067431402

**Comment by vincentrouleau** [comment]
BTW. You should open any other issues in the theme repo instead.
https://github.com/hotdoy/grav-theme-hotdoy

**Comment by phz1** [comment]
Thanks a lot! Fixed it now!

**Comment by vincentrouleau** [comment]
Wonderful! 
Closing.
